name: imagenarte
description: Aplicaci칩n offline-first para tratamiento, protecci칩n y preparaci칩n de im치genes
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  image_picker: ^1.0.7
  path_provider: ^2.1.1
  path: ^1.8.3
  image: ^4.1.3
  exif: ^3.3.0
  crypto: ^3.0.3
  share_plus: ^7.2.1
  google_mlkit_face_detection: ^0.13.1
  
  # Packages locales
  core:
    path: ../../packages/core
  processing:
    path: ../../packages/processing
  watermark:
    path: ../../packages/watermark

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

dependency_overrides:
  image: 3.3.0

flutter:
  uses-material-design: true
