name: watermark
description: Watermark system for Imagen@rte
version: 0.1.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  image: ^4.1.3
  crypto: ^3.0.3
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
