name: processing
description: Image processing pipeline for Imagen@rte
version: 0.1.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  image: ^4.1.3
  google_mlkit_face_detection: ^0.5.0
  core:
    path: ../core

dev_dependencies:
  test: ^1.24.0
